# -*- coding: utf-8 -*-
import base64
import copy
import os
import sys

import cv2

chara_name = {
    "1": "一歌", "2": "咲希", "3": "穗波", "4": "志步",
    "5": "实乃理", "6": "遥", "7": "爱莉", "8": "雫",
    "9": "心羽", "10": "杏", "11": "彰人", "12": "冬弥",
    "13": "司", "14": "笑梦", "15": "宁宁", "16": "类",
    "17": "奏", "18": "真冬", "19": "绘名", "20": "瑞希",
    "21": "MIKU", "22": "RIN", "23": "LEN",
    "24": "LUKA", "25": "MEIKO", "26": "KAITO",
}
staff_style_format = {
    "Name": "staff",
    "Fontname": "思源黑体 CN Bold",
    "Fontsize": 70,
    "PrimaryColour": "&H00715659",
    "SecondaryColour": "&H000000FF",
    "OutlineColour": "&H00FFFFFF",
    "BackColour": "&H00000000",
    "Bold": 0,
    "Italic": 0,
    "Underline": 0,
    "StrikeOut": 0,
    "ScaleX": 100.0,
    "ScaleY": 100.0,
    "Spacing": 0,
    "Angle": 0,
    "BorderStyle": 1,
    "Outline": 5.0,
    "Shadow": 5.0,
    "Alignment": 7,
    "MarginL": 30,
    "MarginR": 30,
    "MarginV": 30,
    "Encoding": 1
}
template_style = {
    "Name": "初音ミク",
    "Fontname": "思源黑体 CN Bold",
    "Fontsize": 83.0,
    "PrimaryColour": "&H00BBCC33",
    "SecondaryColour": "&H000000FF",
    "OutlineColour": "&H00FFFFFF",
    "BackColour": "&H00BBCC33",
    "Bold": 0,
    "Italic": 0,
    "Underline": 0,
    "StrikeOut": 0,
    "ScaleX": 100.0,
    "ScaleY": 100.0,
    "Spacing": 0,
    "Angle": 0,
    "BorderStyle": 1,
    "Outline": 3.0,
    "Shadow": 0,
    "Alignment": 7,
    "MarginL": 325,
    "MarginR": 10,
    "MarginV": 1240,
    "Encoding": 1
}

t = [
    {
        "Name": "初音ミク",
        "PrimaryColour": "&H00BBCC33",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00BBCC33"
    },
    {
        "Name": "鏡音リン",
        "PrimaryColour": "&H0011CCFF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H0011CCFF",

    },
    {
        "Name": "鏡音レン",
        "PrimaryColour": "&H0011EEFF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H000996B5",
        "BackColour": "&H0011EEFF",

    }, {
        "Name": "巡音ルカ",
        "PrimaryColour": "&H00CCBBFF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00BB66FF",
        "BackColour": "&H00CCBBFF",

    }, {
        "Name": "MEIKO",
        "PrimaryColour": "&H004444DD",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H004444DD",
    }, {
        "Name": "KAITO",
        "PrimaryColour": "&H00FF0000",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00FF0000",
    }, {
        "Name": "星乃一歌",
        "PrimaryColour": "&H00EEAA33",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00EEAA33",
    }, {
        "Name": "天馬咲希",
        "PrimaryColour": "&H0043D9FE",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00F17CFD",
        "BackColour": "&H0044DDFF",
    }, {
        "Name": "望月穗波",
        "PrimaryColour": "&H006666EE",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H006666EE",
    }, {
        "Name": "日野森志步",
        "PrimaryColour": "&H0022DDBB",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00828B54",
        "BackColour": "&H0022DDBB",
    }, {
        "Name": "花里みのり",
        "PrimaryColour": "&H00AACCFF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H006B6CC4",
        "BackColour": "&H00AACCFF",
    }, {
        "Name": "桐谷遥",
        "PrimaryColour": "&H00FFCC99",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00B78240",
        "BackColour": "&H00FFCC99",
    }, {
        "Name": "桃井愛莉",
        "PrimaryColour": "&H00CCAAFF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H009454C6",
        "BackColour": "&H00CCAAFF",
    }, {
        "Name": "日野森雫",
        "PrimaryColour": "&H00DDEE99",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H007DA237",
        "BackColour": "&H00DFEFA6",
    }, {
        "Name": "小豆沢こはね",
        "PrimaryColour": "&H009966FF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H009966FF",
    }, {
        "Name": "白石杏",
        "PrimaryColour": "&H00DDBB00",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00DDBB00",
    }, {
        "Name": "東雲彰人",
        "PrimaryColour": "&H002277FF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H002277FF",
    }, {
        "Name": "青柳冬弥",
        "PrimaryColour": "&H00DD7700",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00DD7700",
    }, {
        "Name": "天馬司",
        "PrimaryColour": "&H0000BBFF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H0000BBFF",
    }, {
        "Name": "鳳えむ",
        "PrimaryColour": "&H00BB66FF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00BB66FF",
    }, {
        "Name": "草薙寧々",
        "PrimaryColour": "&H0099DD33",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H0099DD33",
    }, {
        "Name": "神代類",
        "PrimaryColour": "&H00EE88BB",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00EE88BB",
    }, {
        "Name": "宵崎奏",
        "PrimaryColour": "&H008866BB",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H008866BB",
    }, {
        "Name": "朝比奈まふゆ",
        "PrimaryColour": "&H00CC8888",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00CC8888",
    }, {
        "Name": "東雲絵名",
        "PrimaryColour": "&H0088AACC",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H0088AACC",
    }, {
        "Name": "暁山瑞希",
        "PrimaryColour": "&H00CCAADD",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H008866BB",
        "BackColour": "&H00CCAADD",
    }, {
        "Name": "screen",
        "Fontsize": 90.0,
        "PrimaryColour": "&H00FFFFFF",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00000000",
        "BackColour": "&H00000000",
        "MarginL": 10,
        "MarginR": 10,
        "MarginV": 50,
    }, {
        "Name": "関連人物",
        "PrimaryColour": "&H00715659",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00000000",
    }, {
        "Name": "staff",
        "PrimaryColour": "&H00715659",
        "SecondaryColour": "&H000000FF",
        "OutlineColour": "&H00FFFFFF",
        "BackColour": "&H00000000"}, {
        "Name": "screen_address",
        "Fontsize": 67.0,
        "PrimaryColour": "&H00FFFFFF",
        "SecondaryColour": "&H00FFFFFF",
        "OutlineColour": "&H00000000",
        "BackColour": "&H00FFFFFF",
        "MarginL": 15,
        "MarginR": 15,
        "MarginV": 19,
    }, {
        "Name": "screen_dialogue",
        "Fontsize": 67.0,
        "PrimaryColour": "&H00FFFFFF",
        "SecondaryColour": "&H00FFFFFF",
        "OutlineColour": "&H00131314",
        "BackColour": "&H00FFFFFF",
        "MarginL": 15,
        "MarginR": 15,
        "MarginV": 19,
        "Encoding": 1
    }, {
        "Name": "address",
        "PrimaryColour": "&H00FFFFFF",
        "SecondaryColour": "&H00FFFFFF",
        "OutlineColour": "&H00000000",
        "BackColour": "&H00FFFFFF",
        "Alignment": 5,
        "MarginL": 15,
        "MarginR": 15,
        "MarginV": 19,
    }
]

subtitle_styles_format = {}

for item in t:
    it = copy.deepcopy(template_style)
    for key in item.keys():
        it[key] = item.get(key)
    subtitle_styles_format[item["Name"]] = it

DISPLAY_NAME_STYLE = {
    "ミク": "初音ミク",
    "リン": "鏡音リン",
    "レン": "鏡音レン",
    "ルカ": "巡音ルカ",
    "MEIKO": "MEIKO",
    "KAITO": "KAITO",
    "一歌": "星乃一歌",
    "咲希": "天馬咲希",
    "穂波": "望月穗波",
    "志歩": "日野森志步",
    "みのり": "花里みのり",
    "遥": "桐谷遥",
    "愛莉": "桃井愛莉",
    "雫": "日野森雫",
    "こはね": "小豆沢こはね",
    "杏": "白石杏",
    "彰人": "東雲彰人",
    "冬弥": "青柳冬弥",
    "司": "天馬司",
    "えむ": "鳳えむ",
    "寧々": "草薙寧々",
    "類": "神代類",
    "奏": "宵崎奏",
    "まふゆ": "朝比奈まふゆ",
    "絵名": "東雲絵名",
    "瑞希": "暁山瑞希",
    "ミクの声": "初音ミク",
    "リンの声": "鏡音リン",
    "レンの声": "鏡音レン",
    "ルカの声": "巡音ルカ",
    "MEIKOの声": "MEIKO",
    "KAITOの声": "KAITO",
    "一歌の声": "星乃一歌",
    "咲希の声": "天馬咲希",
    "穂波の声": "望月穗波",
    "志歩の声": "日野森志步",
    "みのりの声": "花里みのり",
    "遥の声": "桐谷遥",
    "愛莉の声": "桃井愛莉",
    "雫の声": "日野森雫",
    "こはねの声": "小豆沢こはね",
    "杏の声": "白石杏",
    "彰人の声": "東雲彰人",
    "冬弥の声": "青柳冬弥",
    "司の声": "天馬司",
    "えむの声": "鳳えむ",
    "寧々の声": "草薙寧々",
    "類の声": "神代類",
    "奏の声": "宵崎奏",
    "まふゆの声": "朝比奈まふゆ",
    "絵名の声": "東雲絵名",
    "瑞希の声": "暁山瑞希",
    "？？？": "関連人物",
    "screen": "screen"
}

characterDict = [
    {"name": "ichika",
     "name_j": "一歌"},
    {"name": "saki",
     "name_j": "咲希"},
    {"name": "honami",
     "name_j": "穂波"},
    {"name": "shiho",
     "name_j": "志歩"},
    {"name": "minori",
     "name_j": "みのり"},
    {"name": "haruka",
     "name_j": "遥"},
    {"name": "airi",
     "name_j": "愛莉"},
    {"name": "shizuku",
     "name_j": "雫"},
    {"name": "kohane",
     "name_j": "こはね"},
    {"name": "an",
     "name_j": "杏"},
    {"name": "akito",
     "name_j": "彰人"},
    {"name": "touya",
     "name_j": "冬弥"},
    {"name": "tsukasa",
     "name_j": "司"},
    {"name": "emu",
     "name_j": "えむ"},
    {"name": "nene",
     "name_j": "寧々"},
    {"name": "rui",
     "name_j": "類"},
    {"name": "kanade",
     "name_j": "奏"},
    {"name": "mafuyu",
     "name_j": "まふゆ"},
    {"name": "ena",
     "name_j": "絵名"},
    {"name": "mizuki",
     "name_j": "瑞希"},
    {"name": "miku",
     "name_j": "ミク"},
    {"name": "rin",
     "name_j": "リン"},
    {"name": "len",
     "name_j": "レン"},
    {"name": "luka",
     "name_j": "ルカ"},
    {"name": "meiko",
     "name_j": "MEIKO"},
    {"name": "kaito",
     "name_j": "KAITO"},
    {"name": "miku_band",
     "name_j": "ミク_LeoN"},
    {"name": "miku_idol",
     "name_j": "ミク_MMJ"},
    {"name": "miku_street",
     "name_j": "ミク_VBS"},
    {"name": "miku_park",
     "name_j": "ミク_WS"},
    {"name": "miku_nothing",
     "name_j": "ミク_25"}
]

areaDict = [
    "",
    u"十字路口",
    u"商业街",
    u"购物中心",
    u"音乐商店",
    u"教室的SEKAI",
    "",
    u"舞台的SEKAI",
    u"街道的SEKAI",
    u"奇幻仙境的SEKAI",
    u"空无一人的SEKAI",
    u"神山高中",
    u"凤凰仙境乐园",
    u"宫益坂女子学园"
]


def get_divider_event(string=None, slash=15):
    return [{
        "Type": "Comment",
        "Layer": 1,
        "Start": "00:00:00.00",
        "End": "00:00:00.00",
        "Style": "screen", "Name": '',
        "MarginL": 0, "MarginR": 0, "MarginV": 0,
        "Effect": '',
        "Text": "-" * slash + f"{(' ' + string + ' ') if string else ''}" + "-" * slash
    }]


def get_asset_path(filename=""):
    if getattr(sys, 'frozen', False):
        asset_path = os.path.join(sys._MEIPASS, "asset")
    else:
        asset_path = "asset"
    return asset_path + filename


b64_banner = "iVBORw0KGgoAAAANSUhEUgAABMIAAATCCAYAAABfd0qgAAAACXBIWXMAAAsTAAALEwEAmpwYAAA54UlEQVR4nO3dWXYVubqFUW0DxmBDktH/NgYkrsu4D3nG4XCpXCxbf4TmbMAOweMan+TdsixLAwAAAICN2+t9AAAAAAB4CYYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIZgCAMAAABgCIYwAAAAAIbwuvcBtujg4KBdXl72PgYAAADAJhwcHLTz8/Mn/44iLOz8/NwIBgAAABD06dOnyO8YwsI+f/7c+wgAAAAAm/L3339HfscQFvbly5feRwAAAADYFEVYUYYwAAAAgCxDWFHzPPc+AgAAAMCmTNMU+R1DWJg3wgAAAACyvBFWlKuRAAAAAFmuRhalCAMAAADIMoQVpQgDAAAAyHI1sihDGAAAAECWIqwoVyMBAAAAshRhRSnCAAAAALIUYUUpwgAAAACyFGFFKcIAAAAAslJF2G5ZliXyS7TWWvv48WM7Pj7ufQwAAACATdjb22u3t7eZ34r8Cq211m5vb41gAAAAAEGpGqw1Q1iU98EAAAAAslLvg7VmCIvyPhgAAABAliKsKEUYAAAAQJYhrChFGAAAAECWq5FFGcIAAAAAshRhRbkaCQAAAJClCCtKEQYAAACQpQgrap7n3kcAAAAA2JRpmmK/ZQgLUoQBAAAAZCnCivJGGAAAAECWN8KKUoQBAAAAZCnCilKEAQAAAGQpwopShAEAAABkKcKKUoQBAAAAZBnCilKEAQAAAOQcHh62/f392O8ZwkJOTk7azc1N72MAAAAAbEayBmvNEBbjWiQAAABAVvKh/NYMYTHzPPc+AgAAAMCmTNMU/T1DWIj3wQAAAACyXI0syhAGAAAAkGUIK8obYQAAAABZ3ggrShEGAAAAkKUIK0oRBgAAAJClCCtKEQYAAACQpQgrShEGAAAAkGUIK0oRBgAAAJDlamRRijAAAACALENYUYYwAAAAgCxDWFGGMAAAAIAsQ1hR3ggDAAAAyHnz5k07PDyM/qYhLODq6qqdnZ31PgYAAADAZqT/YmRrhrAI1yIBAAAAstLXIlszhEW4FgkAAACQpQgrShEGAAAAkKUIK0oRBgAAAJClCCtKEQYAAACQZQgryhAGAAAAkDVNU/w3DWEBhjAAAACALG+EFeWNMAAAAIAsVyOLUoQBAAAAZCnCilKEAQAAAGQpwooyhAEAAABkGcKKcjUSAAAAIMvVyKIUYQAAAABZirCiFGEAAAAAWYqwgpZlUYQBAAAABH38+LHt7eVnK0PYE3358qUty9L7GAAAAACbMU3Ts/yuIeyJ1GAAAAAAWc/xPlhrhrAn8z4YAAAAQNZzvA/WmiHsyRRhAAAAAFmKsKIUYQAAAABZirCiFGEAAAAAWYqwogxhAAAAAFmGsKJcjQQAAADIcjWyKEUYAAAAQJYirKh5nnsfAQAAAGBTpml6lt81hD2Rq5EAAAAAWYqwolyNBAAAAMjyRlhRhjAAAACALEVYUa5GAgAAAGQpwopShAEAAADkHBwctIODg2f5bUPYE5ydnbXLy8vexwAAAADYjOeqwVozhD2JGgwAAAAg67neB2vNEPYkhjAAAACALENYUR7KBwAAAMhyNbKoeZ57HwEAAABgU6ZperbfNoQ9gauRAAAAAFmuRhblaiQAAABAliGsKEUYAAAAQJY3wooyhAEAAABkKcKKcjUSAAAAIEsRVpQiDAAAACBLEVaUIgwAAAAgSxFWlCIMAAAAIEsRVpQiDAAAACDrOYuw3bIsy7P9+sZ9/PixHR8f9z4GAAAAwCbs7e2129vb5/v9Z/vljbu5uTGCAQAAAAQ9Zw3WmiHs0bwPBgAAAJD1nO+DtWYIezTvgwEAAABkGcKKUoQBAAAAZLkaWZQhDAAAACBLEVaUq5EAAAAAWYqwohRhAAAAAFmKsKIUYQAAAABZirCiDGEAAAAAWYawogxhAAAAAFmGsKK8EQYAAACQ5Y2wohRhAAAAAFmKsKIUYQAAAABZirCiFGEAAAAAWYawohRhAAAAAFmuRhZlCAMAAADIOTw8bG/evHnWbxjCHuH4+Ljd3Nz0PgYAAADAZjx3DdaaIexRvA8GAAAAkGUIK8oQBgAAAJBlCCvK+2AAAAAAWc/9FyNbM4Q9iiIMAAAAIEsRVpQiDAAAACBLEVaUIgwAAAAgSxFWlCIMAAAAIEsRVpQiDAAAACDLEFaUIgwAAAAgy9XIogxhAAAAAFmKsKLmee59BAAAAIBNmabp2b9hCHsEb4QBAAAAZLkaWZSrkQAAAABZrkYWZQgDAAAAyHnz5k07PDx89u8Ywh7o8vKynZ2d9T4GAAAAwGa8xLXI1gxhD6YGAwAAAMh6iWuRrRnCHsxD+QAAAABZirCiFGEAAAAAWYqwohRhAAAAAFmGsKIUYQAAAABZrkYWNc9z7yMAAAAAbMo0TS/yHUPYAynCAAAAALJcjSzKG2EAAAAAWa5GFqUIAwAAAMhShBVlCAMAAADIMoQV5WokAAAAQJarkUUpwgAAAACyFGFFKcIAAAAAshRhRSnCAAAAALIUYQUty6IIAwAAAAj666+/2t7ey0xUhrAHUIMBAAAAZL3UtcjWDGEPogYDAAAAyDKEFaUIAwAAAMh6qffBWjOEPYgiDAAAACBLEVaUIgwAAAAgSxFWlCEMAAAAIMsQVpSrkQAAAABZrkYWpQgDAAAAyFKEFaUIAwAAAMhShBU1z3PvIwAAAABsiiGsKFcjAQAAALIMYUUZwgAAAACyvBFWlDfCAAAAALIUYUUpwgAAAACyXrII2y3LsrzY11bu7du37erqqvcxAAAAADbh3bt37ezs7MW+pwi7p7OzMyMYAAAAQNBL1mCtGcLuzbVIAAAAgCxDWFEeygcAAADIesmH8lszhN2bIQwAAAAgyxBWlCEMAAAAIMsQVpQhDAAAACDLG2FFeSwfAAAAIEsRVpQhDAAAACBLEVaUq5EAAAAAWYqwohRhAAAAAFmKsKIUYQAAAABZirCiFGEAAAAAWYqwogxhAAAAAFmGsKLmee59BAAAAIBNmabpRb+3W5ZledEvrtSHDx/ayclJ72MAAAAAbMKrV6/azc3Ni35TEXYPNzc3RjAAAACAoJe+FtmaIexe/MVIAAAAgCxDWFEeygcAAADI+vvvv1/8m4awezCEAQAAAGQpwopyNRIAAAAgSxFWlCIMAAAAIEsRVpQiDAAAACBLEVaUIgwAAAAgSxFW1DzPvY8AAAAAsCnTNL34Nw1h96AIAwAAAMhShBXljTAAAACALG+EFaUIAwAAAMhShBWlCAMAAADIMoQVpQgDAAAAyHI1sihDGAAAAEBWjyJstyzL8uJfXZnXr1+329vb3scAAAAA2ISjo6N2fHz84t9VhP3B8fGxEQwAAAAgqEcN1poh7I/mee59BAAAAIBN6fE+WGuGsD/yPhgAAABAliGsqM+fP/c+AgAAAMCmGMKKUoQBAAAAZHkjrChFGAAAAECWIqwoRRgAAABAliKsKEUYAAAAQJYhrChFGAAAAECWq5FFGcIAAAAAshRhRbkaCQAAAJClCCtqnufeRwAAAADYFENYUa5GAgAAAGQZwooyhAEAAABk9XojbLcsy9Llyyvx/v37dn5+3vsYAAAAAJuwv7/fLi8vu3xbEfYbl5eXRjAAAACAoF41WGuGsN/yFyMBAAAAsnq9D9aaIey3vA8GAAAAkKUIK0oRBgAAAJBlCCtKEQYAAACQ5WpkUYowAAAAgCxDWFGGMAAAAIAsQ1hRhjAAAACALG+EFeWNMAAAAIAsRVhRhjAAAACALEVYUa5GAgAAAGQpwopShAEAAABkKcKKUoQBAAAAZCnCilKEAQAAAGQpwopShAEAAABkGcIKWpZFEQYAAAAQ9OnTp7a312+OMoT9ghoMAAAAIKvn+2CtGcJ+SQ0GAAAAkNXzWmRrhrBfUoQBAAAAZBnCilKEAQAAAGS5GlmUIQwAAAAgSxFWlKuRAAAAAFmKsKIUYQAAAABZirCiFGEAAAAAWYqwogxhAAAAAFmKsKIMYQAAAABZ0zR1/b4h7Be8EQYAAACQpQgrShEGAAAAkOWNsKIUYQAAAABZirCiFGEAAAAAWYawohRhAAAAADnv3r1rBwcHXc9gCPuJ09PTdnV11fsYAAAAAJvRuwZrzRD2U2owAAAAgKzeD+W3Zgj7KUMYAAAAQJYirKh5nnsfAQAAAGBTpmnqfQRD2M/4i5EAAAAAWYqwolyNBAAAAMjyRlhRhjAAAACALEVYUa5GAgAAAGQpwopShAEAAABkKcKKUoQBAAAAZBnCilKEAQAAAGS5GlmUIgwAAAAgSxFWlCIMAAAAIEsRVtQ8z72PAAAAALAp0zT1PoIh7GcUYQAAAAA5r169ah8+fOh9DEPY/3d9fd1OTk56HwMAAABgMyq8D9aaIewHajAAAACArArvg7VmCPuBIQwAAAAgSxFW1OfPn3sfAQAAAGBTFGFFKcIAAAAAshRhRSnCAAAAALIMYUUpwgAAAACyXI0sap7n3kcAAAAA2BRDWFGKMAAAAIAsQ1hR3ggDAAAAyDKEFaUIAwAAAMjyWH5RijAAAACALENYUYowAAAAgCxXI4syhAEAAABkKcKKcjUSAAAAIEsRVpQiDAAAACDn6OiovX79uvcxWmuGsO98/fq13d7e9j4GAAAAwGZUuRbZmiHsO/M89z4CAAAAwKZM09T7CP9lCPsfrkUCAAAAZFV5H6w1Q9h3DGEAAAAAWa5GFuUvRgIAAABkKcKKUoQBAAAAZCnCilKEAQAAAGQZwopShAEAAABkuRpZlCEMAAAAIEsRVpSrkQAAAABZirCiDGEAAAAAWYqwogxhAAAAAFnTNPU+wn8Zwv6HIQwAAAAgSxFWlMfyAQAAALK8EVaUIQwAAAAgZ39/v71//773Mf7LEPYfFxcX7fz8vPcxAAAAADajUg3WmiHsv9RgAAAAAFmV3gdrzRD2Xx7KBwAAAMgyhBWlCAMAAADIcjWyKEMYAAAAQJYirKh5nnsfAQAAAGBTpmnqfYTvGML+wxthAAAAAFmKsKJcjQQAAADI8kZYUYowAAAAgCxFWFGKMAAAAIAsRVhRhjAAAACALEVYUa5GAgAAAGQpwopShAEAAABkKcKKUoQBAAAAZBnCilKEAQAAAGS5GlnQ3d2dIQwAAAAg6O+//2673a73Mb5jCGtqMAAAAIC0atciWzOEtda8DwYAAACQZggrShEGAAAAkFXtfbDWDGGtNUUYAAAAQJoirChFGAAAAECWIqwoQxgAAABAliKsKFcjAQAAALIUYUUpwgAAAACyFGFFzfPc+wgAAAAAm6IIK0oRBgAAAJBlCCvKG2EAAAAAWYawohRhAAAAAFneCCtKEQYAAACQZQgrShEGAAAAkFXxauRuWZal9yF629/fb9fX172PAQAAALAJ7969a2dnZ72P8YPhi7DT01MjGAAAAEBQxRqsNUOYa5EAAAAAYRXfB2vNEOahfAAAAIAwRVhR8zz3PgIAAADAphjCinI1EgAAACDLEFaUIQwAAAAgyxthRXkjDAAAACBLEVaUIgwAAAAgSxFWlCIMAAAAIMsQVpQiDAAAACDL1ciiFGEAAAAAWYqwohRhAAAAAFmKsKIUYQAAAABZhrCiDGEAAAAAWVWHsN2yLEvvQ/R0dHTUTk9Pex8DAAAAYBNevXrVbm5ueh/jp4Yuwq6vr41gAAAAAEFVa7DWBh/CPJQPAAAAkFX1L0a2NvgQ5n0wAAAAgCxFWFGKMAAAAIAsRVhRijAAAACALENYUYowAAAAgCxXI4tShAEAAABkKcKKMoQBAAAAZE3T1PsIv2QIAwAAACDG1ciivBEGAAAAkOVqZFGKMAAAAIAsQ1hRijAAAACALFcjizKEAQAAAGQpwopyNRIAAAAgSxFWlCIMAAAAIKtyEbZblmXpfYheXr161e7u7nofAwAAAGATjo6O2vHxce9j/NKwRdg///xjBAMAAAAIqnwtsrWBhzDvgwEAAABkTdPU+wi/NewQ5n0wAAAAgKzK74O1NvAQpggDAAAAyHI1sihFGAAAAECWIqwoRRgAAABAliGsKEUYAAAAQJarkUUZwgAAAACyFGFFuRoJAAAAkKUIK0oRBgAAAJClCCtqnufeRwAAAADYFEVYUa5GAgAAAGQZwopyNRIAAAAgyxBWlCEMAAAAIKv6G2G7ZVmW3ofo4d27d+3i4qL3MQAAAAA2YX9/v11eXvY+xm8NWYRdXFwYwQAAAACCql+LbG3QIcxD+QAAAABZ1a9FtjboEOZ9MAAAAIAsRVhRhjAAAACALEVYUa5GAgAAAGQpwoqa57n3EQAAAAA2xRBWlKuRAAAAAFmGsKJcjQQAAADI8kZYUYowAAAAgCxFWFGGMAAAAIAsRVhRrkYCAAAAZBnCilKEAQAAAGS5GlmUIgwAAAAgSxFWlCIMAAAAIEsRVpQiDAAAACBnt9spwiq6u7tr//zzT+9jAAAAAGzGp0+f2m63632MPxpuCFODAQAAAGStoQZrbcAhzPtgAAAAAFlreB+stQGHMEUYAAAAQJYirChFGAAAAECWIqwoQxgAAABAliKsKFcjAQAAALIMYUUpwgAAAACyXI0sShEGAAAAkKUIK8oQBgAAAJA1TVPvI9yLIQwAAACAJ3E1sihvhAEAAABkuRpZlCIMAAAAIMsQVpQiDAAAACDL1ciiFGEAAAAAWYqwohRhAAAAADnv379vb9++7X2MexlqCDs9PW3X19e9jwEAAACwGWupwVobbAhzLRIAAAAgyxBWlCEMAAAAIGstD+W3ZggDAAAA4Ammaep9hHsbagjzUD4AAABAlquRRSnCAAAAALJcjSxKEQYAAACQpQgrShEGAAAAkGUIK0oRBgAAAJDlamRRijAAAACALEVYUYowAAAAgCxFWFGGMAAAAIAsRVhR8zz3PgIAAADApijCivJGGAAAAECWIawoVyMBAAAAcl6/ft0+fPjQ+xj3NswQdn193U5PT3sfAwAAAGAz1vQ+WGsDDWGuRQIAAABkrelaZGsDDWGuRQIAAABkKcKKUoQBAAAAZBnCilKEAQAAAGS5GlmUIgwAAAAgSxFWlCIMAAAAIEsRVtQ8z72PAAAAALAphrCiFGEAAAAAWYaworwRBgAAAJDljbCiFGEAAAAAWYqwogxhAAAAAFmKsKJcjQQAAADIUoQVpQgDAAAAyFKEFaUIAwAAAMgyhBWlCAMAAADI+fDhQ3v9+nXvYzzIEEPYly9f2t3dXe9jAAAAAGzG2t4Ha22gIQwAAACAHENYUd4HAwAAAMha2/tgrQ0yhCnCAAAAALIUYUUpwgAAAACyFGFFKcIAAAAAshRhRRnCAAAAALIUYUW5GgkAAACQpQgrShEGAAAAkKUIK0oRBgAAAJBlCCtqnufeRwAAAADYlGmaeh/hwYYYwlyNBAAAAMjyRlhRhjAAAACALFcji/JGGAAAAECWIawoRRgAAABAztu3b9v79+97H+PBNj+EnZ+ft4uLi97HAAAAANiMNdZgrQ0whKnBAAAAALLW+FB+a4YwAAAAAB5IEVaUh/IBAAAAshRhRRnCAAAAALIUYUUZwgAAAACypmnqfYRHMYQBAAAA8CCKsKI8lg8AAACQ5Y2wogxhAAAAAFmKsKJcjQQAAADIMoQVpQgDAAAAyHI1sihFGAAAAECWIqwoRRgAAABAliKsKEMYAAAAQNZai7DdsixL70M8p7/++qt9/fq19zEAAAAANmG327W7u7vex3iUTRdht7e3RjAAAACAoLXWYK1tfAhzLRIAAAAga63vg7W28SHMX4wEAAAAyFKEFaUIAwAAAMhShBVlCAMAAADIUoQV5WokAAAAQJYhrChFGAAAAECWq5FFKcIAAAAAshRhRSnCAAAAALIUYUXN89z7CAAAAACbMk1T7yM82qaHMEUYAAAAQJarkUV5IwwAAAAgyxBWlCIMAAAAIMsbYUUpwgAAAACyFGFFKcIAAAAAshRhRRnCAAAAAHLev3/f9vf3ex/j0TY7hJ2cnLTr6+vexwAAAADYjDVfi2xtw0OYGgwAAAAga83XIlvb8BA2z3PvIwAAAABsiiGsKEUYAAAAQJYhrKjPnz/3PgIAAADAphjCilKEAQAAAGR5LL8oRRgAAABAliGsKEUYAAAAQJarkUUpwgAAAACyFGFFKcIAAAAAshRhRRnCAAAAALIUYUW5GgkAAACQZQgrap7n3kcAAAAA2JRpmnof4Uk2O4S5GgkAAACQtfY3wnbLsiy9D/EcDg8P29nZWe9jAAAAAGzC69ev2/X1de9jPMkmi7CrqysjGAAAAEDQ2muw1jY6hLkWCQAAAJC19ofyW9voEOYvRgIAAABkGcKKUoQBAAAAZLkaWZQiDAAAACBLEVaUIgwAAAAgSxFWlCIMAAAAIEsRVpQhDAAAACBrmqbeR3gyQxgAAAAAf6QIK8obYQAAAABZ3ggrShEGAAAAkKUIK0oRBgAAAJClCCvKEAYAAACQpQgrytVIAAAAgCxDWFGKMAAAAICsLVyN3C3LsvQ+RNre3l7b4D8LAAAAoIsPHz60r1+/9j7Gk22uCPvy5YsRDAAAACBomqbeR4jY3BDmfTAAAACArC28D9baBocw74MBAAAAZG3hfbDWNjiEKcIAAAAAshRhRSnCAAAAALIUYUUpwgAAAACyFGFFKcIAAAAAshRhRRnCAAAAALIUYUW5GgkAAACQZQgryhAGAAAAkOVqZFGGMAAAAICsaZp6HyFic0OYN8IAAAAAslyNLEoRBgAAAJBlCCtKEQYAAACQtZU3wnbLsiy9D5F0cHDQLi8vex8DAAAAYBPevn3bLi4ueh8jYlNF2Pn5uREMAAAAIGgrNVhrGxvCvA8GAAAAkLWV98Fa29gQ5n0wAAAAgCxFWFGGMAAAAIAsRVhR8zz3PgIAAADApijCivJGGAAAAECWIawoVyMBAAAAsgxhRRnCAAAAALK8EVaUq5EAAAAAWYawohRhAAAAAFmuRhalCAMAAADIUoQVpQgDAAAAyFKEFaUIAwAAAMhShBWlCAMAAADI2tIQtluWZel9iJSPHz+24+Pj3scAAAAA2ITdbtfu7u56HyNmM0XY7e2tEQwAAAAgaEvvg7W2oSHM+2AAAAAAWVu6FtnahoYw74MBAAAAZCnCijKEAQAAAGQpwopyNRIAAAAgyxBWlCIMAAAAIMvVyKIUYQAAAABZirCiFGEAAAAAWYqwouZ57n0EAAAAgE1RhBWlCAMAAADImqap9xGiNjOEeSMMAAAAIEsRVpQiDAAAACDLG2FFKcIAAAAAshRhRSnCAAAAALIUYUUZwgAAAACytlaE7ZZlWXofIuHNmzft5uam9zEAAAAANuH9+/ft9PS09zGiNlGEnZycGMEAAAAAgrZ2LbK1jQxhHsoHAAAAyNratcjWNjKEzfPc+wgAAAAAmzJNU+8jxG1iCPNQPgAAAECWIqwoQxgAAABAljfCivJGGAAAAECWIqwoRRgAAABAliKsKEUYAAAAQJYirChFGAAAAECWIqwoQxgAAABAliKsKFcjAQAAALIMYUUZwgAAAACyXI0syhAGAAAAkDVNU+8jxBnCAAAAAPjBFq9G7pZlWXof4qkODw/b2dlZ72MAAAAAbMLr16/b9fV172PErb4Iu7q6MoIBAAAABG3xfbDWNjCEuRYJAAAAkLXFa5GtbWAI+/LlS+8jAAAAAGyKIqwoRRgAAABAliKsKEUYAAAAQJYirChDGAAAAECWIqyoeZ57HwEAAABgUxRhRXkjDAAAACDLEFaUq5EAAAAAWYawohRhAAAAAFneCCtKEQYAAACQZQgryhAGAAAAkOVqZFGuRgIAAABkKcKKUoQBAAAAZCnCilKEAQAAAGQpwopShAEAAADkfPz4sb169ar3MZ7Fqoewz58/t2VZeh8DAAAAYDO2ei2ytZUPYWowAAAAgCxDWFHeBwMAAADI2ur7YK2tfAhThAEAAABkKcKKUoQBAAAAZCnCilKEAQAAAGQZwooyhAEAAABkuRpZlKuRAAAAAFmKsKIUYQAAAABZirCi5nnufQQAAACATTGEFaUIAwAAAMgyhBXljTAAAACALG+EFaUIAwAAAMhShBWlCAMAAADIUoQVpQgDAAAAyDk4OGjv3r3rfYxns9oh7OzsrF1eXvY+BgAAAMBmbLkGa23FQ5gaDAAAACDLEFaUIQwAAAAga8sP5be24iHMQ/kAAAAAWYqwouZ57n0EAAAAgE2Zpqn3EZ7VaocwVyMBAAAAslyNLMoQBgAAAJDlamRR3ggDAAAAyDKEFaUIAwAAAMhyNbIoRRgAAABAliKsKEUYAAAAQJYirChFGAAAAECWIqwoRRgAAABAliGsKEUYAAAAQNbWr0bulmVZeh/iMT5+/NiOj497HwMAAABgE/b29trt7W3vYzyrVRZhNzc3RjAAAACAoK1fi2xtpUOY98EAAAAAsrZ+LbI1QxgAAAAATRFWlofyAQAAALIMYUUpwgAAAACyXI0sShEGAAAAkKUIK0oRBgAAAJClCCtKEQYAAACQpQgryhAGAAAAkKUIK8oQBgAAAJBlCCvKG2EAAAAAWYawohRhAAAAAFneCCtKEQYAAACQpQgryhAGAAAAkKUIK8rVSAAAAIAsQ1hRijAAAACAnMPDw7a/v9/7GM9udUPY8fFxu7m56X0MAAAAgM0YoQZrbYVDmGuRAAAAAFkjPJTfmiEMAAAAYHiGsKK8DwYAAACQZQgrShEGAAAAkOWNsKIUYQAAAABZirCiFGEAAAAAWYqwohRhAAAAAFmKsKIMYQAAAABZirCiXI0EAAAAyDKEFaUIAwAAAMhyNbKoeZ57HwEAAABgUwxhRbkaCQAAAJBlCCvK1UgAAACALG+EFWUIAwAAAMh58+ZNOzo66n2MF7GqIezy8rKdnZ31PgYAAADAZoxSg7W2siFMDQYAAACQNcr7YK2tbAjzUD4AAABAliKsKEUYAAAAQJYirChDGAAAAECWIqwoVyMBAAAAsgxhRc3z3PsIAAAAAJsyTVPvI7yYVQ1hrkYCAAAAZHkjrChXIwEAAACyXI0sShEGAAAAkGUIK8oQBgAAAJDlamRRrkYCAAAAZCnCilKEAQAAAGQpwopShAEAAABkKcKKUoQBAAAAZCnCClqWxRAGAAAAEPTx48e2t7eaeejJVvMv/fLlS1uWpfcxAAAAADZjmqbeR3hRqxnCvA8GAAAAkDXS+2CtrWgIcy0SAAAAIGuk98FaW9EQpggDAAAAyFKEFaUIAwAAAMgyhBVlCAMAAADIcjWyKFcjAQAAALIUYUUpwgAAAACyFGFFKcIAAAAAshRhRRnCAAAAALKmaep9hBdlCAMAAAAYlCKsKG+EAQAAAGR5I6woRRgAAABAliKsKEUYAAAAQNZoRdhuWZal9yHu4+3bt+3q6qr3MQAAAAA24eDgoJ2fn/c+xotaRRF2dnZmBAMAAAAIGu1aZGsrGcJciwQAAADIGu1aZGsrGcI8lA8AAACQpQgryhAGAAAAkKUIK8oQBgAAAJA1TVPvI7y4VQxh3ggDAAAAyHI1sihFGAAAAECWIawoRRgAAABAljfCilKEAQAAAGQpwopShAEAAABkKcKKUoQBAAAAZCnCilKEAQAAAGQZwooyhAEAAABkuRpZ1DzPvY8AAAAAsCkjDmG7ZVmW3of4kw8fPrSTk5PexwAAAADYhL29vXZ7e9v7GC+ufBF2c3NjBAMAAAAIGrEGa20FQ5j3wQAAAACyRnwov7UVDGGfP3/ufQQAAACATTGEFaUIAwAAAMhyNbIoRRgAAABAliKsKEUYAAAAQJYirChFGAAAAECWIqwoRRgAAABAliGsqHmeex8BAAAAYFOmaep9hC7KD2GKMAAAAIAsb4QV5Y0wAAAAgCxXI4tShAEAAABkKcKKMoQBAAAAZCnCinI1EgAAACDLEFaUIgwAAAAga9SrkbtlWZbeh/id169ft9vb297HAAAAANiEw8PDdnJy0vsYXZQuwo6Pj41gAAAAAEGj1mCtFR/C5nnufQQAAACATRn1fbDWig9h3gcDAAAAyJqmqfcRuik9hPmLkQAAAABZirCiFGEAAAAAWd4IK0oRBgAAAJClCCtKEQYAAACQZQgryhAGAAAAkOVqZFGuRgIAAABkKcKKUoQBAAAAZCnCilKEAQAAAGQpwoqa57n3EQAAAAA2ZZqm3kfopvQQ5mokAAAAQJYirChDGAAAAEDWyG+E7ZZlWXof4lfev3/fzs/Pex8DAAAAYBPevHnTrq6ueh+jm7JF2OXlpREMAAAAIGjkGqy1wkOYvxgJAAAAkDXy+2CtFR7CvA8GAAAAkGUIK0oRBgAAAJDlamRRijAAAACALEVYUYowAAAAgCxFWFGGMAAAAICsaZp6H6ErQxgAAADAIFyNLMobYQAAAABZhrCiDGEAAAAAWd4IK8rVSAAAAIAsRVhRijAAAACALEVYUYowAAAAgCxFWFGKMAAAAIAsQ1hRijAAAACALFcjC1qWRREGAAAAEPTXX3+1vb2SU9CLKfmvV4MBAAAAZI1eg7VWdAhTgwEAAABkGcKKDmGKMAAAAICs0R/Kb63oEKYIAwAAAMgyhBnCAAAAAIbgamTRIczVSAAAAIAsRVjRIUwRBgAAAJClCCs6hCnCAAAAALIUYYYwAAAAgCEYwgxhAAAAAEOYpqn3EborOYR5IwwAAAAgyxthRYcwRRgAAABAlquRRYcwRRgAAABAliKs6BCmCAMAAADIUoS1tluWZel9iP/v7du37erqqvcxAAAAADbh4OCgnZ+f9z5Gd+WKsLOzMyMYAAAAQJBrkf8qN4S5FgkAAACQ5Vrkv8oNYR7KBwAAAMhShP2r3BA2z3PvIwAAAABsiiLsX+WGMFcjAQAAALKmaep9hBLKDWGuRgIAAABkKcL+ZQgDAAAA2DhvhP2r3BDmaiQAAABAliLsX+WGMEUYAAAAQJYi7F/lhjBFGAAAAECWIuxf5YYwRRgAAABAliHsX4YwAAAAgI1zNfJf5YYwVyMBAAAAshRh/yo3hM3z3PsIAAAAAJsyTVPvI5SwW5Zl6X2I//Xhw4d2cnLS+xgAAAAAm7C3t9dub297H6OEUkXY9fW1EQwAAAAgyPtg35QawjyUDwAAAJDlfbBvDGEAAAAAG6YI+6bUEOYvRgIAAABkKcK+KTWEKcIAAAAAshRh35QawhRhAAAAAFmKsG9KDWGKMAAAAIAsQ9g3pYYwRRgAAABAlquR3xjCAAAAADZsmqbeRyjDEAYAAACwYa5GflNqCPNGGAAAAECWIeybUkOYIgwAAAAgyxth35QawhRhAAAAAFmKsG8MYQAAAAAbpgj7ptQQ5mokAAAAQJYi7JtSQ5giDAAAACDn6OiovXnzpvcxyigzhH39+rXd3t72PgYAAADAZqjBvldmCHMtEgAAACDL+2DfM4QBAAAAbJQh7HtlhjDvgwEAAABkGcK+V2YIU4QBAAAAZHkj7HtlhjBFGAAAAECWIex7ZYYwRRgAAABAlquR3yszhCnCAAAAALIUYd8zhAEAAABslCLse2WGMFcjAQAAALIUYd8zhAEAAABslCLse4YwAAAAgI0yhH2vzBDmjTAAAACALEPY98oMYYowAAAAgCxvhH2vzBCmCAMAAADI2d/fb4eHh72PUUqJIezi4qKdn5/3PgYAAADAZqjBflRiCFODAQAAAGQZwn5UYgjzPhgAAABAlofyf1RiCFOEAQAAAGQpwn5kCAMAAADYIEXYj0oMYfM89z4CAAAAwKYYwn5UYgjzRhgAAABAliHsRyWGMFcjAQAAALK8EfYjQxgAAADABinCflRiCHM1EgAAACBLEfajEkOYIgwAAAAgSxH2oxJDmCIMAAAAIEsR9qMSQ5giDAAAACDLEPajEkOYIgwAAAAgy9XIH5UYwhRhAAAAAFmKsB91H8Lu7u4MYQAAAABBnz59ant73Wefcrr/jxjBAAAAALJci/y57kOY98EAAAAAslyL/LnuQ5giDAAAACDLEPZzhjAAAACAjXE18ue6D2GuRgIAAABkKcJ+rvsQpggDAAAAyFKE/Vz3IUwRBgAAAJClCPu57kOYIgwAAAAgyxD2c92HsHmeex8BAAAAYFNcjfy57kOYIgwAAAAga5qm3kcoqfsQ5o0wAAAAgCxXI3+u+xCmCAMAAADIcjXy57oPYYowAAAAgCxF2M91H8IUYQAAAABZhrCfM4QBAAAAbMi7d+/awcFB72OU1HUIOz09bVdXVz2PAAAAALAparBf6zqEqcEAAAAAsjyU/2tdhzAP5QMAAABkKcJ+resQNs9zz88DAAAAbI4i7NdcjQQAAADYEEPYrxnCAAAAADbEEPZr3ggDAAAA2BBvhP2aIgwAAABgQxRhv6YIAwAAANgQRdivKcIAAAAANsQQ9muGMAAAAIANcTXy11yNBAAAANgQRdivGcIAAAAANkQR9muGMAAAAIANMYT92m5ZlqXXx4+Ojtrp6WmvzwMAAABsyqtXr9rNzU3vY5TVrQi7vr42ggEAAAAEeR/s97oNYf5iJAAAAECWa5G/120I8z4YAAAAQJYi7PcUYQAAAAAboQj7PUUYAAAAwEYown5PEQYAAACwEYaw3zOEAQAAAGyEq5G/120Im+e516cBAAAANskQ9nveCAMAAADYCEPY77kaCQAAALAR3gj7PUUYAAAAwEYown5PEQYAAACwEYqw3zOEAQAAAGyEIuz3XI0EAAAA2AhF2O8pwgAAAAA2QhH2e7tlWZYeH3716lW7u7vr8WkAAACAzTk6OmrHx8e9j1FalyLs69evRjAAAACAINci/6zLEDbPc4/PAgAAAGzWNE29j1BelyHM+2AAAAAAWd4H+7MuQ5i/GAkAAACQ5WrknynCAAAAADbAEPZnijAAAACADXA18s8UYQAAAAAboAj7M0MYAAAAwAYowv7M1UgAAACADVCE/ZkiDAAAAGADFGF/1mUIm+e5x2cBAAAANksR9meKMAAAAIANmKap9xHK80YYAAAAwAYowv5MEQYAAACwAd4I+7PdsizLS3/03bt37eLi4qU/CwAAALBJ+/v77fLysvcxynvxIuzi4sIIBgAAABDkWuT9vPgQ5n0wAAAAgCzXIu/nxYcw74MBAAAAZCnC7scQBgAAALByirD7cTUSAAAAYOUUYffz4kPYPM8v/UkAAACATVOE3Y+rkQAAAAArZwi7H0MYAAAAwMoZwu7HG2EAAAAAK+eNsPtRhAEAAACsnCLsfhRhAAAAACunCLsfRRgAAADAyhnC7kcRBgAAALByrkbejyIMAAAAYOUUYfejCAMAAABYOUXY/bzoEHZ3d9f++eefl/wkAAAAwKZ9+vSp7Xa73sdYhRcdwtRgAAAAAFlqsPt70SHM+2AAAAAAWd4Huz9DGAAAAMCKKcLuz9VIAAAAgBVThN2fIgwAAABgxRRh96cIAwAAAFgxRdj9KcIAAAAAVswQdn+KMAAAAIAVczXy/gxhAAAAACtmCLs/QxgAAADAihnC7s8bYQAAAAAr5o2w+1OEAQAAAKyYIuz+FGEAAAAAK6YIuz9DGAAAAMCKKcLub7csy/JSH9vf32/X19cv9TkAAACATXv37l07OzvrfYzVeLEi7PT01AgGAAAAEKQGe5gXG8I8lA8AAACQ5X2whzGEAQAAAKyUIexhDGEAAAAAKzVNU+8jrMqLDWH+YiQAAABAljfCHkYRBgAAALBSrkY+jCIMAAAAYKUMYQ+jCAMAAABYKVcjH0YRBgAAALBSirCHMYQBAAAArJQi7GFcjQQAAABYKUXYwyjCAAAAAFZKEfYwLzaEzfP8Up8CAAAAGIIi7GFcjQQAAABYqWmaeh9hVXbLsiwv8aGjo6N2enr6Ep8CAAAA2LxXr161m5ub3sdYlRcpwq6vr41gAAAAAEHeB3u4FxnCXIsEAAAAyPI+2MO9yBDmL0YCAAAAZBnCHk4RBgAAALBCrkY+nCIMAAAAYIUUYQ9nCAMAAABYIUXYw7kaCQAAALBCirCHe5EhbJ7nl/gMAAAAwDCmaep9hNVxNRIAAABghRRhD+dqJAAAAMAKeSPs4RRhAAAAACukCHs4QxgAAADACinCHs7VSAAAAIAVUoQ9nCIMAAAAYIUMYQ+nCAMAAABYIVcjH263LMvy3B959epVu7u7e+7PAAAAAAzh6OioHR8f9z7G6jx7EfbPP/8YwQAAAACC1GCP8+xDmGuRAAAAAFnTNPU+wioZwgAAAABWxkP5j/PsQ5i/GAkAAACQZQh7HEUYAAAAwMp4I+xxFGEAAAAAK6MIexxDGAAAAMDKKMIex9VIAAAAgJVRhD2OIgwAAABgZQxhj6MIAwAAAFgZVyMfxxAGAAAAsDKGsMcxhAEAAACsjCHscbwRBgAAALAyhrDHUYQBAAAArIzH8h9ntyzL8pwfePfuXbu4uHjOTwAAAAAMY39/v11eXvY+xio9axF2fn5uBAMAAAAIci3y8Z51CPM+GAAAAECWa5GPZwgDAAAAWBFF2OM96xDmoXwAAACALEXY4xnCAAAAAFbEEPZ4hjAAAACAFZmmqfcRVssQBgAAALAi3gh7PI/lAwAAAKyIq5GPZwgDAAAAWBFF2OO5GgkAAACwIoqwx1OEAQAAAKyIIezxFGEAAAAAK+Jq5OMpwgAAAABWRBH2eIYwAAAAgBVRhD3eblmW5bl+/K+//mpfv359rp8HAAAAGM7d3V3b7Xa9j7FKz1aE3d7eGsEAAAAAgv7++28j2BM82xDmWiQAAABAlvfBnubZhjB/MRIAAAAgy/tgT6MIAwAAAFgJRdjTGMIAAAAAVkIR9jSuRgIAAACshCLsaRRhAAAAACthCHsaRRgAAADASrga+TSKMAAAAICVUIQ9zbMNYfM8P9dPAwAAAAxpmqbeR1g1RRgAAADASijCnsYbYQAAAAAr4Y2wp1GEAQAAAKyEIuxpFGEAAAAAK6EIexpFGAAAAMBKKMKexhAGAAAAsALv379vb9++7X2MVXuWIezk5KRdX18/x08DAAAADEkN9nTPMoSpwQAAAACyDGFP9yxD2DzPz/GzAAAAAMPyUP7TKcIAAAAAVmCapt5HWL1nGcI+f/78HD8LAAAAMCxXI59OEQYAAACwAoawp1OEAQAAAKyAN8KeThEGAAAAsAKKsKdThAEAAACsgCLs6RRhAAAAACugCHs6QxgAAADACijCns7VSAAAAIAVUIQ93bMMYfM8P8fPAgAAAAxLEfZ0rkYCAAAArIAh7OkMYQAAAADFvX79un348KH3MVYvPoRdXV2109PT9M8CAAAADMv7YBnxIUwNBgAAAJBlCMuID2H+YiQAAABAlvfBMhRhAAAAAMUpwjIUYQAAAADFKcIyFGEAAAAAxSnCMhRhAAAAAMUpwjIMYQAAAADFGcIyDGEAAAAAxRnCMrwRBgAAAFCcN8IyDGEAAAAAxSnCMlyNBAAAAChOEZahCAMAAAAozhCWoQgDAAAAKM7VyAxFGAAAAEBxirCM3bIsS/IH9/b2WvgnAQAAAIb14cOH9vXr197H2IRoEfblyxcjGAAAAECQa5E50SHM+2AAAAAAWYawnHgRBgAAAECO98FyFGEAAAAAhSnCchRhAAAAAIUpwnIMYQAAAACFKcJyXI0EAAAAKEwRlqMIAwAAACjMEJajCAMAAAAozNXIHEMYAAAAQGGKsBxDGAAAAEBh0zT1PsJmeCMMAAAAoDBXI3MUYQAAAACFuRqZowgDAAAAKMwQlrNblmVJ/djBwUG7vLxM/RwAAADA0N6+fdsuLi56H2MzokMYAAAAAFQVvRoJAAAAAFUZwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCEYwgAAAAAYgiEMAAAAgCH8H5NqucDe4hjHAAAAAElFTkSuQmCC"
b64_menu = "iVBORw0KGgoAAAANSUhEUgAAAEEAAABBCAIAAAABlV4SAAAACXBIWXMAAAsTAAALEwEAmpwYAAAGlmlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNy4xLWMwMDAgNzkuYjBmOGJlOSwgMjAyMS8xMi8wOC0xOToxMToyMiAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDIzLjIgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyMi0wNi0yNlQwMDo1MTozMiswODowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjItMTAtMDRUMTU6MTE6MjUrMDg6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjItMTAtMDRUMTU6MTE6MjUrMDg6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmEyNGNlY2VjLTllNTAtZDA0ZS04MGZhLTVmYzA5OTA5ZmVlNiIgeG1wTU06RG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOjhkMmUzOTQ4LTA4ZmMtMjY0Mi05OTg3LTA5NTZlNDQ4OWU2MCIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjBlNTg0NGUzLTc2YjAtZTI0Ny05MTNlLTkwMDUyYjQwYmUzNiI+IDx4bXBNTTpIaXN0b3J5PiA8cmRmOlNlcT4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImNyZWF0ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MGU1ODQ0ZTMtNzZiMC1lMjQ3LTkxM2UtOTAwNTJiNDBiZTM2IiBzdEV2dDp3aGVuPSIyMDIyLTA2LTI2VDAwOjUxOjMyKzA4OjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgMjMuMiAoV2luZG93cykiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjFjMGU0NGM3LWE0ZWMtYjg0Ni1hMzk4LTczNjg3ZTUyMjMxYiIgc3RFdnQ6d2hlbj0iMjAyMi0xMC0wNFQxNTowNjowOCswODowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDIzLjIgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDphMjRjZWNlYy05ZTUwLWQwNGUtODBmYS01ZmMwOTkwOWZlZTYiIHN0RXZ0OndoZW49IjIwMjItMTAtMDRUMTU6MTE6MjUrMDg6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCAyMy4yIChXaW5kb3dzKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz5LHeMfAAAQRElEQVRogc1bW5NUR3LOS9XpM8y158ZFArHiIgnJSCCJlXYdsbGr3fWDww6HV7ERfrBf7J9gsf/Jjn2w117birAkpGUlELdBeIAFRoLhNjeYYbqn+5yqzPRDdTcNDJhBMytXdHR09PQ5lV9VZeaXX57B+bl5RAQAAFDVzud1HGaW3s2MiLz3IQRAJCIiLooCEZgxzR5j9I4BHjUDV/sSAIA6RpvZRgCA9tI455xzACAiZsbMIcZmUWSV3AAByflKswjHjx9P5jz9/amzSBthfWsOIuccMyNiejczEWFmACjLMssqZSnffDP9m9/8x8cff/qEJV91uA21Pg0RISIzCyEwc8JjgGbI7EOIy/dWLl+empg4e/bsV3fu3F7r/d0GnZ/ugYiIqKreewAwM1UFdMTeFBfm75w/f/HEiVPT0zfuLdWI1myP2wCbHxjJE9JnZg4hAAAREWX1lTAzM3vs2PFjx04szC8CYAiWZf+/MCAYmIGZAZqqJucmohjjzMzMtenZo0d/f+bMGSZvBgBYqeSIca3TbBQGRDSF5JpERESKZAqmZMB37yxOTl767W8/mpmZZc5CULMUXdS573If0NTS0SciEYF2uEMkEVMF5gwAFu/W/vmf/v3Cxamlew2AzJQQjB0BKICmK1a9/8ZjSNYixRiZob0DKUoiszOTxcXaHy5Offjhf9+6OVurN9UYkQEI0UwNEAAM8UnmbjAGABE1A2ZHRCEERHSOEakoSiK8dvXGsWMnJycvXf3mmnMZIhHSWs1ddaznWcqySozROZ/eVTWEqAox2sULk0eOHL169cbC/BKRazYLJEfcYgmq+gwhdX0xYGIGySAzIOKyLJ1zAHbz5szlS1dPnz578eJliSCSKFNWlJFd+r0R0ZrIxUZgSANjFFUzAxH1PhORqamvvzz+1amTkwsLd0WU2SGSiAIkuxNJ+1YAYJ0wGGDLp4mcGZRlKIpiamrqs88+u3B++u6d4BybgRl4z6oGQEysLQDfdjwLhscwXAJwABYDFE05fvz0kSOf3rx5MwbvXY9ozLIMQBFNVQHAMRIYrPL6o2CAFtnMAICIYhQERGSJaEZXrkx99NGR85N/WFxc8r43y1yz2fTeM6MqmZn3bGYIZmCqkZlUJUqoVLIsy37wg0ONRiPPc+dcjPFp6NwzYDAAY6ZKpdJoNFRVxVKMX15emZj46tixL7/5ejpGqFT6VSzG6Bwhmkg0wxSvkvNLDHleKcumgeQV3rx55L33fnLg4Ct5nhPR0xdkz4KBCGKUsiyd881GM8tyAJq+duv06ckzZ85OX7tRluJ9LqKmQIxETkTTxY3GinM+BSLnWCT6zA0MDL7++mv797+2a9f3+gdydpLOW6o0NgIDlGXpfUWiEhGAM+OjR7+Y/J9L09O3b928bYbMrKoxRu8rqonDpWzNaYHNjMhCKJ2nzZu3HDiw/9Chg9t3PKcaVaNFSZzlKWubZ8CAWVaRCAAcI95ZqE1Onjp69IvZ2flmI4SgzrWKhJQfmNnMiEBEUvI2U++9SNyydXTbtq2vvPLSW2+/MTo6BCBEJiLUBvCU5fGzYCiKwpTLMkxfuz0xMXn82Kl6vWg0GswEgGag2qpvEYGIQohEyJyYqYkIAG/ZOvbaa3vffvutnTt3bOqtiJQhFIiQ55UQyzUZtHYMhqa0uLg8NXXt6O++vHL5eq3W9L6HOSOyRJmwTYSYHXPKABZjFIn9/b09PZVt27a+8+6BNw68MjJSJUKR0kycY2aOMSK0LlkXDNbmZIlNpM9ucXHpyCeff/bZ75nzoohEjpCDFEiUFArVVhIA1DYPN2Yiojx3u3Z/75e/fH9waBNxyHuyZrPhHBdl9N6VsXTMicM//ao+jKHrCFrShBDJFETMe2+GVy5f//DDTy6cv7hSlxiXmT2iqQXnnaowuxAiABAxM4tIFARDYhApt+/Y/LOf/ejgm6/nuUMKeU8WpckOREP6MREaGODaMt0DGLrRm5mZiiiTVwVVqtWKo7/7/MyZ87dv3V1crIsIIjJDh7EhcYhC7MysVYSChVAw0dDQwKuvvnzg4L6XXt65aVNGLOy8gQKAmmrbfQ0MzNbKYO9jeGj7ENEMKpVcIhRFWVsuPv7406++mrx5Y9a5PE2ZeFtnJGdQNVVxjrLMixCY7Hzh+TcO/Mmrr768detIb58PoSkSARGJWxoHQOf0P4NU5x5a+24UhL4sdGWlOXHm/NTU9ZMnT9drTeeyRqMBAEmtaF9iBtiuGQKiAWhRrlSrQ6/ue+mVl3fv2/fS8PBQGeqIllW8iAFAShTdK9jav7ViSJJb0rDSjVpeaCwCMzMLp0+dPXXq3LWrt0RABBCj9x67Qnh7CdHMVGOeewNxDnfseH7//tdefmnXzp3bvHdIwXsykBgCgBFjR2LszmjPoHe1zhIRIWJZltCWIeq18sb1uRMnTk1MnLt7pwbgVIXJIylAd73fyaamGs0EEMHi7t17fvin7xw8+Hpfb6Us6oiSalQDZXZmen+78T6YtVp/H4P3PjlollVCGZjdjRvXr1y++cnHX1y9er3ZKIl8pdIjUiKQaiSCFGfbRznZYoBKDJs25Xv27PzZz3+8Z88uAAmhiahErCohBCImQgRSawVuM31m6zsYDNEQzUwR2Tlfr6188fmXRz75cvFukWQV57gsi7ThDp2ZAKCqdlf0quI8jY0Nv/fej9/9wVs9Pc45MAM1AQQgMDAkElVAAgQRJeYE4CE/tvb7A975RAxKBCKRmUIoVOjXv/6X48dP3VsqY3RE4Jw3UxEhYmanCgAEAETc7ZSEuGP79u+/8+ahQ29WKowYzZCIwJDZtzYNrSNldOxL8e3+VjzGH+zxMPjw4X8UCcwUYyTyzmXj41sbK2FhYaleL5PQKxITVyNCREoYzJL/JYdEAKvVlpvNFe9o69ZRImFO4pcLMbRsZQZENVMzonb92mV0y7kBANHaf+7swxMwfEBEzvmyDIisin19A8MjI9XqWNEM9XotZbq08ADA7FWhrcZh9/1j1Gajcev2zbn52z092eDgoJok04i4LZ+5rnj6wKKvGp3waTD86leHAcAMiZjIMbmiKEZHR6vVkbHxcbW4uLhQFoVzXkSyrCLSHVQeOBNZVhGJjUb9+vS1Wv2emY2NjbFjVXXOJTPaRdzDmlJ3sG5v7FNjOPzBBzEGAAJAREZA752ZZJVscHBgeHiwLJvNoli8u9jTs6koykSoETtHqHOYUM1iDACopgvzC7NzcyHEnp6eSp4RUVr9dlfuvpVpdFJ+555rwXD4AyJiZlUDAyIE1CilY/YZj4wOv/DCjt5NfaI6PzevasyuzY3b925/MEvSPIuImq7UG1euXGk0Guyov7+/p6enc3ge8tv7SfrBb54ew2EzA0CVVqMgxsCMasKOVGTTpk1btmwdG9s8NzcXQyzLCB0MCAAtaoBkAIqIiKwqYCgiRbOYnbs9O3fbe9/b2+u9Zyai1TP0o6jWgIEInfOOnc+8iHjfav4RUxRhduzc2Njo9985tFy7d29peaVRtG/ZFoUQAJSZEt9pz05mFqPcW7o3NzsvUft6+6rVKiKaKoARAmHSaAwREIAQAQxbG2VJBm9b/1gSgvNz893BNxWQ0K4eEn4zBEAVaxbF7Zv3/u1fP7py5cry8nJaSOdchzilCk5VAEBVACyVBMTmHG7bNv6L9/9yz54X+/o2AapImShC6vYm3Kl7/Wg9jY/fCT58+HD331LIb5ne/tJAARTJvKfh6ujI8FiWuYWFuRhDjDHGWKnkqVWVWreJt6etQGQwNgWJ2mw2r1y+PDs719/Xn1cqWeYQMAlhyWhqrZ91n6XOPjwZw+qjO5V6n0QhIKTR0eHRserIaHWlsVKrrZhhs1kmpohIiImGtHgkABBhkmRUpF5fmZtduHZ1GhCq1SHnMiJHSKkOgratKWlClz98WwzQpncpiIqUfX2bRkaqw8MjRFyr1dIJ1HYd3I3BTM00nTcRVTVVWFi4u3j3brNo5nnvwMAgAIkoGCISEgHYumFoR/77qSDBITLvXZ5XNm/ZPDY2llVcbfneyspKjGmtBdslXlpaVUmXMzsAQiAArtfrc3Nzy8srRRGHhqp5njO7luOidmb71hhWxQXgmNJ6IuJQdXD3rhcNJERZWqwlu9NDDADAzJ1k7JxLsk16gdnS0tKtW7fn5uYdu6HqUG9vX4KMeF9pXXcMmEQa0xbdMBOR0me0ffuWwYHhZlOLogghpNZOcgyz1qFKQlOykjkxSLIWkltEPDAwiISIxrxKfnhGDPjwq0VTwSBJRlnFA6hoqOT+uW0vvPjiXmKs15fLsiiKQk2TCWbKzOlEJREkjRDEsVOxer1x6dLlixf/MD6+eWioP8vu84CnwZDyw+pj1eIKHyM9mFUAKmURLl2e+q///PDChUvNZuldZqaOW+05VWtzcBdjQIQYxTknEp2jsmwOVfvfOLD37//hbx4z8+rjSa2kR/ahTbVXz5gCGCo9/OKu5//qr//i53/2Xm9fHqRAghBKEUmmp/ibOneqYIZmBMBmzJzVlhvnzk0CYBe3xyfsQBrr1lM0EFVTgSxzO3duz/O8Wh2amDj79dS12r0VMw1BUlIvywAA7Wx4v4IjohjD3NziWqdeNwyIgGDs0FQA4PnntwwO9vX19/T19p07e6FWq5uBSGw/dsKqkmWZGaSKqkPIe/Ke7wxDi58hBgmEhsh5zvv27R7sHxiuDp+fvHDz5q0YKbmEGTBzjIHIpRKvLIuyLPLcm5WPOat/DAzATCKaZV5EkNRnNOB7HT83Njq+dev4qVOnv/lmurbciFFijJVKhdmJJK1SnWNEH6NoKNY673r22EU08SJmLsuC2ZmBczi+eWh4+O3Nm0dOnJiYODO5uHjPrHTOFUVhBonmm6XI6zSubRPWE4OZaftJw5QCW20hMbPoPL2yb+/QUBURJyfPLy0tx9BqDKRErqqqkmUOyT96Z0zU+zFjHdr0aSBCalilFAYAIYQQylTNxFjGWIyND/7i/T//2797f/eebaINQnNMoKoSwYzQTEu1+JAyYGqtiugxY+OeI+tMa0mYUo3MDBD27v1etfqLo5+dPPHludnZ+dSuL4rgPYmUjz78YO1k8TgU67YPD83bXaZ2182JDo6MjLz77qGf/vRHO3Zsy/MkfkKMqkox6v9184fHhj9XCQAd62OMnedyR8aqB998rTo8MHHm3MmTZ+7cWapU8hijz77L/PDoaCtFZkmc7TzBkOe5Y2Jy+/fvfe65zaNj1ZMnznz99dUYY4j1tU6z0fuAKaqIxPQZoPXEq0qhWhDZ6NjgD394aGho4JNPPp2Zma3VS1hjR27Dz5KZdVptiU0QkUisZC5EIVIiHRjseffdt8fHh8+d++rY8c8BCExbSB4Qdlf36vXEsNrqWYflJsk5hJDUg2ZZZlkmYiLRuUzVdu/Zue25sSKsPHDPzr8FPGHeuZl5TELUIz/r5i3dtYhEWR3BaiAQMKleHfdIYUo1qAVEInSI1PkXiZYggNBWBgBTv+bx5+t/AbPLJA5UmXJsAAAAAElFTkSuQmCC"
b64_place = "iVBORw0KGgoAAAANSUhEUgAAAC0AAABBCAIAAADKTrrsAAAHP0lEQVRoBb3Ba1NU9wHH8e/voCgGL4AKTDTxFgkieInXeIlRhz2rubWjplZIm0xj3TVNkzi5tUnaPOob6LNOX0BfUZ90JjNJm6uiyLILe875/8qiTgBBMWH5fGRn/BTC4sHE/Mk2UxnEvJiHEPMnB3M/8XDmIcT8yTYLyyAelf75j38xnbExc7EbljQIt7a2LF++rLn5sQ0bNjzxZAf3sS2J+dFTm/uZznLDkiiEwP1EY2NjpTLasmZVSJP17es6O9e3t6/ftHlTR/vKjU8+vrOnZ9nyiOlsMBMUMRe9ePZtZlIAMYsQAiApS5NILpVGKpWRJK1KdHSs7ehY19W1bWdvz57dOzsfb5OY4MAdhihiLsrnrzKTMBIzmEmmxo6EpDQdb2iITLg5dMMEO21qWnbw4P5jx48dfravtbWZe0JwFIk5KB9f5dEJCVFjCGDwhBDSanV8+PbQli1bDhzYtaNn6/Hjx5pXLuFhlI+v8sgkJO4wBO6xHZwIl0qjptLe0Xby5HP9/c9ve2ojD6R8XOA+kqgxsxAIS4gag5lkcAiB0NAQhSwk6Whl7PayxqV9u7ovDVzYv6+XuSmfLzCDmYcIRI2ZSjgEA8YkWVZN02q5Mryrr+dXF8+fOnmAOSgfX2EmgXgIMTc7cIeMXU1GS6PDXdu3Dw6cO3HiwNLGiPsoHxeYSWAQD2IeREhY1Biy0XKpVBrZ0b1pcOB8f3yE+ygfX2Umg/m5IpCN7UgKhKSaDA9/3f305jcvv3H8uT1Mp3x8lZnMAhDIxjYgKYqiscrNcmVoz56+Dz54e9PmDqZQPr7KNAaxYMQUdjJye+ixlU2HDu56/4O3mpsbuUf5uEhdiBpzl0ChJrWDGX39jYuvXjizZEkDk5SPi9SFqDE/isDgJEmv3/iqZ+fWzz77aPtTjzNJ+bjIorAjCWOCbg5/19Skixd/efnyq0xSPi6ySCJqohCcJOXbI0MHD+75/PN329qaAeXjIoskoiYKwWlaHb51o6Vt5fnzJ998cwBQPi6ySAQCbLIsGxsbrYyVDx7c/te/XFu7rlX5uMiikk2WpVmWjo2Nr1rFu+/87uTpo8rHRerGIKYJBteAq0l66+aX5y+cuXatqHxcZHGFYGqMov9++e/+/iMf/+ma8nGRujHTiJoQDNgBNDLy3Y7uTYOvXVA+LlI3ZhpRE4IB26Dbw992dq45deqo8nGRujHTiJoQjMAYV8dGm5qinp6tysdF6sbMJGpCMCAxPjZWLt/etq1D+bhI3ZhZCEIwWFKWZsO3rjevlOK4yE8l5mQmmRkEiBAMBuFQKY+YkuK4SB2IGptZCAeDQbJv3PgejSqOi9SBqLGZhXAwmAmmNHILlRXHRerHzEI4GAxy5pGRWytXRYpzRRaZcAhMEMlYmqXJE5taFeeK1IOoMbMQDgE0oTw62ri0Yd++bsW5IovODoAUlUvD7e1tJ54/oDhXZJEJB4Ml3fjhmx07tgwMnlecK1JHZibZgUkhZCMjN/bv6/30s/cV54rUkZlKxthMMCTV8dLod4OD565cGVScK1JHZipZ2FaWBcT4eGX1Gr/3XuHY0UOKc0XqyEwl2xluyGrSL774z+n+A3//+9+WNS5VnCtSF+Z+ck2IQkjHxssiy5898vFHbwGKcwXqQtSYHwmwg0NUTco3b13fs7f3ww8LT3dtBBTnCiyqKMtcLg83LPGlS+cvX34FMCjOFag/25JCCJKSJBsa+nbv3p4/f/rOls3tgEFxrkBdKIoUbOxgY6IGHBxFDd98+3Vr64rB1y5c+vULS5c2MElxrkBdKIoUDA4hGCw5C1maVrO0+tyJQ++8e6WtdTn3KM4VqCPZIQSDEZXKyM2bP+zbv/uTT/64besGplCcK1BPtkMItrMQbt/+4clNna+/PvDC2aOAqRE1inMF6skO1WoSQrh+/cbuPd0DA+f6c/sjMSGAQNQozhVYGAYxnSBJxqpJdXh4uGt7129+e+7M2UNMMjXiLsW5AgvGTGULDw1dL1dKXU9vGxwYeOmVw8xBca7AwhA1AgN2yJJqqTTStGLZoYO7T/cfP3lqP3NTnCuwAGQDmpBmiUNWrpRCmrS1rj5zJn7pleMbn2jnHtuSmE5xrshPYgcbTbIFSGRpOnTz+2q18ljzigP7n3n55bOHD/c0rVjCJNuSmI3i3FUeiUFMCCFQY6khy9IkSST97+uvtm/fvP/A7s7Otc8e2ruzdwtTGcSslI//wJzMLORJaZqOjpbsLEmqlUolTcd7+7p37OjevXvHqdNH1qxuBGxLYh60u+8XzElMZ0iSqiTjVStXtratWbd27bp1LW1tLe2dbV1dW/t6tzQ3L2eSQcyXXnzx98zJ3CeE0Ni4tLFxaXv7+paWNS0ta/Y+09fX17t6FVOZGjFfss3CMZi7BGK+lDnwKIS4x9wRqDF3RSBAIOZLmc3PZTA1EVMIxHwp2CyAAAIxnZiv/wMGkHVT/G0oBgAAAABJRU5ErkJggg=="
b64_point = "iVBORw0KGgoAAAANSUhEUgAAACsAAAArCAIAAABuP+aXAAAACXBIWXMAAAsTAAALEwEAmpwYAAAFyWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNy4xLWMwMDAgNzkuYjBmOGJlOSwgMjAyMS8xMi8wOC0xOToxMToyMiAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDIzLjIgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyMi0wNi0yNVQwNDoyMjoxNyswODowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjItMDYtMjZUMDA6NTA6MDQrMDg6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjItMDYtMjZUMDA6NTA6MDQrMDg6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmVlNGZjNGZhLTdkMGUtZmM0Yy1iMTBkLTA4MGZmODg1ZjZlZSIgeG1wTU06RG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOmQ0ZGYyMDk3LTA3ZTktMGM0MC1hNzBjLWE1MzYzYzVlNGY4ZSIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjM4YjYzZWFiLThiZWYtNTc0Yy1hMzJlLTZkMmYwNzFiMTQ5MyI+IDx4bXBNTTpIaXN0b3J5PiA8cmRmOlNlcT4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImNyZWF0ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MzhiNjNlYWItOGJlZi01NzRjLWEzMmUtNmQyZjA3MWIxNDkzIiBzdEV2dDp3aGVuPSIyMDIyLTA2LTI1VDA0OjIyOjE3KzA4OjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgMjMuMiAoV2luZG93cykiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmVlNGZjNGZhLTdkMGUtZmM0Yy1iMTBkLTA4MGZmODg1ZjZlZSIgc3RFdnQ6d2hlbj0iMjAyMi0wNi0yNlQwMDo1MDowNCswODowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDIzLjIgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pj6WFq4AAAdoSURBVFiFpZhbbxvHFYDPmZm98CbedKMlRRIl25Kt2K6loE6R1IBhAwnaAC360ocC7VOQn9L/0Jc+9iFoERRFWvehSJqkjh3L8iWq5diyRZGmRFIUr7va2d2ZPpASKXJFUu7BeeHszJxvZs5lhvjxx7+HAQTRo82ro+z83dnQKWwQ891i+ZRSIrw3Fa1HfShkNFuZ3MjpNUuKToOIfSDehIDrytZSInV5Ij8dq0d9KCCeKRth39z9bV/ZwC6I3nJqAq6x1IWx/16fy83EBaONxvxbUTOoohAzD9L+sklOA0GXl28O0q/hB7ZKMwtjDz9Y2JuKCEaPvEMiOirdPzPETCdQPlAsBwdmGHgPEBxGd2bj936xVB4NSYIdX12FVoaD9z66KBDmH6SDZXPA4xiMAMFRaG4q+sXv3jGHdOkVGE3R1Ps/vygIWbi75a+ag+yEB0H3/LbGdufi//nVFSMcaFu9BBAdPQVK0OmTW+eA4uI3m/6q5Tlhe3R4+EHHAK6x7NmR1Z9dLI8PuQrtvaDGooVKyqMhQUlkp6pyp/eQPgRcV1IXxtc+WNybiroK805CXQSA6GisFvPbKotmK70hehFYPmVrKbF+fX5vZiDzLQIAQLR9Sj3SH+JEAsunbC2defpeMp+MtQfeoASHELWo31ZYLFthtuM5hTdBI+s9fS+ZS8YEIwD4JgRNCLUyEhISormaYrvd0eFBYPtYemFs/frZ3FxcKBQQvfcfEaBTveoXCo3lpyKqaQf3DYU7KI/1Yx2DHIVmz418f+NsfibmKoexKiXKzsCTwKiL1HYFQUdTDpt5N64gUviVtQ8XiRDJtUygbBLRyil0ZaW1B45Cd2eG7390cW8q5qrHzh67yi4REN6tjb3I6TXLiAQkJQCA4HptFwCCUEhudlivHoT2DYW3jqNF4Ci0MBH7/JP3q2NBwUjHjnYSSBgq1Be/2PjRX9eimVJpIlKPBgDxRILGZigkNzus1e2hQu0oOpoEjdV//sn7jkKBeRx8B4Fm8OkHqemHaa1u6TVr9EW+OBM3wn7AzsPqhGCkMBVlXESzVWa7TQJHZenziS9/vWIFVEDoS6DV+Nv/3Dj77St/qY5SIoBi2aMvcs+vzUvarxIgCJWUJkKSkVimymyHrqzcLJ4Jrf90dnd6pNmpJ4FW45dub8yvpv1lAw7dE6XUDD7+fHd/Msx9qiQ9oxdRMuIyUE0rnqkQKaEWDbxeGANFNhUlQLcCAPhMZ+Vv63OrGV/VYgJVt6WaDZPP8lf//mwkVaKOlIhtSjrUpbQ4Ed1NDksJBABslZlDOlBo6gnmUQJ1nDMbeX/lACUgIJWdOr657y8dEFceyxPYqYIQy6ceBDQAIACgWnagZPY5PwCJwFW6uTxhhHXPDtzHti+MVuMBQUnf2VSD+ysWNHKiRGLrrDwe6lF8G6fqMrr3VlixnGDR0EwbD+u8ROB+ZXN58vGNc6VGEe+ZxBl3R1/uJe+nIztVurx8U6vzYNGoxfyV0WDn9es4QQOiMB1RD5xg0VC4A4CCUq4rqUuJ7365VI2HBCM9zKME6op4unTuztb0oyx1BF1evokAeo0Pb5dyc3FjSO/7OmlASIqhfJ1yWQ/5d+eGv/nNFUmJy1jvGsYcN7JTXfxyM7maUU0OR5UJATTDnn6Y/eHdGVfxqMUdv11G96ajLmORdK0wG/36t1cO2/sQhAr1t//xbPZBWjd5o4VeXbnVqHJESuqKqSc7hZmIFdAkIkpoKkIzxI/7c3UkuHU1sX0pwXWFq6rjZR6FZJZLHNHQdz57Mv0wo5v2UT+6vHKrscaGSc2wh7cr5fGAEdYlaXNpj5Whq1DuV7mmCHJYR7oJJBC36bA/+dPq1OOsVrMR2mpjk6A1QPpq1lDBNMK6EfW14sqLABDl0a6c0K1BQG333U8fTj3O6jWOUraP8LitM8cdfbm39C8kQmQWRh3lDV+3R6LXrMu3n06vZdR6K4Bb5jzHMNtJPC9IgiggfeENIVACtd3wbnX+zqu5u9uqwbvuGCcTAADjTuJZHgAkgfTimKOeGoLabixdmr+zNXcvpdb5iYa6m45AFe4kNvIgpEtJ5vzo0Uu5h6CQR+PDu9W5b1PJu9u64XF1axF0H0zLTSUw7o7/UEBX2ArJJ4fbE/4xdzoUwt3GhIF9M3kvNX93S6tzJL0uDb1KiESQCMx2x18Ur/1lPZIpEafPFaghes1a+OrFwr83tdqJmz8QwZFQxx3ZLt7442ooX+kLQW338u2n579+NYj5QQkAgLgikqvc+sN3kdcl4vaC+PGfHyXvbavGQObB+z+UEyoTSqmZfHi7sj8eMMO6pG3lQwJ1RbBoXPt0bfJJVqvZ7W+j3s+tUxBAW8ash/V61CdpMzqIEEOF+tXPvp9c39HrvMO7T03g8Rhr+0pc4atY/pIBCNzPJAH1wB55VVz46uXMo9eayYmU2HUx6yGnzjMSkNlO4vmebtgTGzlbV9CVoWI9niprJkcpB3nk/18EDQPMcUdSpZFU6dTDu+R/XiSJ9eiZVLoAAAAASUVORK5CYII="
